# -*- coding: utf-8 -*-
"""Aula1003

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1So_fYct9M-kRt1dVW2Gw-DM5c58t378r
"""

a = 10
b = 20
c = a + b
print(c)
c += 10
print(c)

#A diferença entre um arquivo .ipynb é um formato específico de um notebook 
#Python, já o .py é o formato padrão.

a = input(prompt = "Digite seu nome ")
print("Bem vindo(a)", a)

## Testando 

media1 = float(input("Digite a primeira nota do aluno "))
media2 = float(input("Digite a segunda nota do aluno "))
mediafinal = (media1 + media2) / 2

##Precisa converter SEMPRE caso queira receber algo e fazer cálculos

print("A média final é ", mediafinal)

nome = input("Digite seu nome ")
idade = int(input("Digite sua idade "))
print("Bem vindo(a) aos testes", nome, "Sua idade é", idade)

num1 = int(input("Digite um número inteiro "))
num2 = int(input("Digite outro número inteiro "))
num3 = num1 // num2
print("O resultado INTEIRO da divisão é ", num3)

#Desafio que criei pra mim mesma: fazer uma calculadora simples em Python
#Passar para o GitHub